### ISSUE TITLE
RDS 高可用与单机 zone 字段适配

### ISSUE THREAD

**Issue by HoweChen** [WeBankPartners/wecube-plugins-alicloud#111]
CMDB 当中 单机实例的 zone 也会采用 含有MAZ的格式，但是创建单机的时候只会传一条记录

单机: ap-southeast-maz1-a
高可用 ap-southeast-maz1-a, ap-southeast-maz1-b

**Comment by yolanda0209** [comment]
alicloud_v0.7.3版本测试通过。
