### ISSUE TITLE
创建snat rule报错[eip [161.117.9.233] not bind natgateway is unsupported.]

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-alicloud#113]
创建snat rule报错：eip已绑定nat gateway的时候，调用接口创建snat rule报错[eip [161.117.9.233] not bind natgateway is unsupported.]
![image](https://user-images.githubusercontent.com/17095701/81164015-342ccc80-8fc2-11ea-8052-a81d91715f32.png)

**Comment by HoweChen** [comment]
Same reason of #115

**Comment by yolanda0209** [comment]
alicloud_v0.7.7版本测试通过。
