### ISSUE TITLE
创建rds高可用版报错"system errors:The given coreMemoryString doesn't match all available resources."

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-alicloud#118]
创建rds高可用版报错"system errors:The given coreMemoryString doesn't match all available resources."。
![image](https://user-images.githubusercontent.com/17095701/81176404-b1af0780-8fd7-11ea-8271-38bea387a470.png)

**Comment by HoweChen** [comment]
目前不支持插件自动帮用户匹配最佳资源，会在 #125 中完成
