### ISSUE TITLE
创建rds返回 "errorMessage": "Alicloud cannot find the required resources."

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-alicloud#136]
创建rds返回 "errorMessage": "Alicloud cannot find the required resources."
{"callbackParameter":"0033_0000000001",
"accountDescription":"mysql1",
"seed":"Seed1234",
"accountName":"root",
"dBTimeZone":null,
"securityGroupId":"sg-t4n50r0dljy77va2ypbj",
"dBInstanceSpec":"2C4G",
"payType":"PostPaid",
"engine":"MySQL",
"vSwitchId":"vsw-t4n8yua2hy7fq0o12v9ub",
"vpcId":"vpc-t4njvl763vsuevl4alun8",
"autoRenew":"false",
"zoneId":"[ap-southeast-1MAZ1-a,
ap-southeast-1MAZ1-b]",
"cloudParams":"regionId=ap-southeast-1",
"dBInstanceDescription":"csmysql1",
"engineVersion":"5.7",
"identityParams":"xxx",
"period":"month",
"dBInstanceClass":null,
"securityIPList":"[10.128.40.1,
10.128.40.2,
10.128.40.3,
10.128.40.4,
10.128.40.5,
10.128.40.6,
10.128.40.7,
10.128.40.8]",
"privateIpAddress":"10.128.40.2",
"dBInstanceStorageType":"cloud_ssd",
"usedTime":null,
"dBInstanceStorage":"50",
"guid":"0033_0000000001",
"category":"HighAvailability",
"accountPassword":"Abcd1234",
"dBInstanceId":"",
"dBIsIgnoreCase":"0"}

**Comment by HoweChen** [comment]
相关资源查找与阿里云的参数配置有关。

现在已经在 #125 支持cpu和内存的动态查找。

关闭issue
