### ISSUE TITLE
阿里云插件接口返回结果的格式不对

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-alicloud#40]
阿里云插件接口返回结果的格式不对。
![image](https://user-images.githubusercontent.com/17095701/79294678-54102980-7f09-11ea-8a84-fd6fb8c316c2.png)
![image](https://user-images.githubusercontent.com/17095701/79294722-6db17100-7f09-11ea-9ce5-37b0dae8f022.png)

**Comment by HoweChen** [comment]
Issue fixed: https://github.com/WeBankPartners/wecube-plugins-alicloud/commit/ca967720d65cea03772f4fc7c3babe75e17579d8
