### ISSUE TITLE
创建VM 与 RDS 应支持通用的规格类型

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-alicloud#46]
创建VM应支持通用的规格类型，如1C2G、2C4G等等.

**Comment by HoweChen** [comment]
根据可用区，zone，cpu和内存找到最适合的机器

将

https://help.aliyun.com/document_detail/66186.html?spm=a2c4g.11186623.2.30.4edd2eafEMqwb9

这个api 打包成一个组件

如果没有找到结果，就找最接近的机器

把最后的cpu和内存作为出参返回

**Comment by HoweChen** [comment]
RDS 与 VM 实现类似，因RDS查询可用资源不包含核心与内存的查询。

所以需要根据一个现有的查询，查询到所有的可用资源，然后去匹配用户输入的xCxG字符串
