### ISSUE TITLE
资源需要支持标签字段

### ISSUE THREAD

**Issue by HoweChen** [WeBankPartners/wecube-plugins-alicloud#58]
目前已知资源有：

- [x] VM
- [ ] RDS

需要支持标签字段，需要针对json的list object做适配

**Comment by HoweChen** [comment]
目前支持标签的格式为：

a=b;c=d 或 a=b

**Comment by HoweChen** [comment]
RDS 资源没有tag字段，issue can be closed.

**Comment by yolanda0209** [comment]
alicloud_v0.7.17测试通过。
