### ISSUE TITLE
插件接口非必填项传空值时调用报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-alicloud#62]
**描述您遇到的bug**  
插件接口非必填项传空值时调用报错。
![image](https://user-images.githubusercontent.com/17095701/80189792-d7d2c000-8645-11ea-8423-ca020d6b4815.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by HoweChen** [comment]
目前阿里云的某些资源，传非法值（例如空值）时会走默认值逻辑，某些资源没有。

所以建议wecube在设定的时候传递Null，即可所有资源都走默认值了。
