### ISSUE TITLE
Ali云创建snat rule的多个外网ip需要共享带宽

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-alicloud#77]
Ali云创建snat rule的多个外网ip需要共享带宽。
![image](https://user-images.githubusercontent.com/17095701/80589795-7481cd00-8a4d-11ea-8ba8-b1f502d3ceb2.png)

**Comment by HoweChen** [comment]
讨论结果，创建eip的时候，默认创建一个共享带宽，把创建好的eip加入进新创建的共享带宽中。

如果请求当中带有共享带宽的名字，（先去查询是否有该名字的共享带宽存在），如果存在，则把新创建的eip，放到这个已存在的共享带宽中。

**Comment by HoweChen** [comment]
解决办法：
在创建eip的时候，通过传入cbpName，将创建好的eip加入cbp
