### ISSUE TITLE
创建SNAT的时候根据入参的外网ip自动绑定natgateway，删除SNAT的时候自动解绑

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-alicloud#81]
创建SNAT的时候根据入参的外网ip自动绑定natgateway，没有绑定就需要先绑定；
删除SNAT的时候自动解绑。

![image](https://user-images.githubusercontent.com/17095701/80852601-7372ba80-8c5c-11ea-8749-feab989ea2ac.png)

**Comment by HoweChen** [comment]
目前问题为sourceVSwitchId  和  sourceCIDR 字段互斥，需要提供更多信息

**Comment by yolanda0209** [comment]
#103

**Comment by yolanda0209** [comment]
alicloud_v0.7.7版本测试通过。
