### ISSUE TITLE
创建RDS的zoneid入参需适配wecube的格式

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-alicloud#82]
创建RDS的zoneid入参需适配cmdb的格式。
wecube入参格式如下：
"zoneId":"[ap-southeast-1MAZ2-b,
ap-southeast-1MAZ2-c]"

**Comment by HoweChen** [comment]
需要拼成类似于 

ap-southeast-1MAZ2(b,c)
ap-southeast-1MAZ3(a,b,c)
ap-southeast-1MAZ1(a,b)

这样的格式
