### ISSUE TITLE
建议rds修改白名单的接口分成两个接口， 一个是增加白名单（只增加入参的ip）， 一个是删除白名单（只删除入参的ip）。

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-alicloud#98]
建议rds修改白名单的接口分成两个接口， 一个是增加白名单（只增加入参的ip）， 一个是删除白名单（只删除入参的ip）。

**Comment by yolanda0209** [comment]
Append IP白名单报错"errorMessage":"system errors:AliCloud server error: [The Specified same security IP already exists.]"}

**Comment by HoweChen** [comment]
Issue fixed.
